### ISSUE TITLE
code review by sig-auth

### ISSUE THREAD

**Issue by mikedanese** [deislabs/secrets-store-csi-driver#92]
Starting as a running list as I review the code here for https://github.com/kubernetes/org/issues/1245.

**Comment by mikedanese** [comment]
* adding csi driver capabilities is not threadsafe. [This](https://github.com/deislabs/secrets-store-csi-driver/blob/3047a16f3cd02466a4e8151d845cbf623dd4e2b3/pkg/csi-common/driver.go#L83) can race with multiple writers or if reading while a concurrent write is executing.
* log redaction of secrets is fragile. [This](https://github.com/deislabs/secrets-store-csi-driver/blob/3047a16f3cd02466a4e8151d845cbf623dd4e2b3/pkg/csi-common/utils.go#L108-L131) is complex and is whitelist based.
* Controller server races. [Read](https://github.com/deislabs/secrets-store-csi-driver/blob/3047a16f3cd02466a4e8151d845cbf623dd4e2b3/pkg/secrets-store/utils.go#L45) operations need to hold the lock that guards cs.vols.
  * stylistic comment: Put all of controllerServer methods in the file where controllerServer is declared. Some of them are in utils.go, and controllerserver.go is short enough.
* stylistic: move [init](https://github.com/deislabs/secrets-store-csi-driver/blob/51d64fcf33d62b84143f666ed8bc387011652de5/pkg/secrets-store-csi-driver/main.go#L28-L33) into [handle](https://github.com/deislabs/secrets-store-csi-driver/blob/3047a16f3cd02466a4e8151d845cbf623dd4e2b3/pkg/secrets-store-csi-driver/main.go#L52-L55). Does os.Exit(0) at the end of the main do anything? It looks like it should be removed.
* sytlisitc: move main packages out of pkg/ and into a cmd/ directory to designate that they are not shared packages.
* Why use atomic [here](https://github.com/deislabs/secrets-store-csi-driver/blob/3047a16f3cd02466a4e8151d845cbf623dd4e2b3/pkg/secrets-store/controllerserver.go#L62-L70)? Counter doesn't survive restarts. Is that a problem? It looks pretty easy to add volumes with name conflicts.

Questions:
* Why are driver options passed with a [mix](https://github.com/deislabs/secrets-store-csi-driver/blob/51d64fcf33d62b84143f666ed8bc387011652de5/pkg/secrets-store-csi-driver/main.go#L44-L46) of env variables and command line arguments?
* What is `mock_provider` [here](https://github.com/deislabs/secrets-store-csi-driver/blob/3047a16f3cd02466a4e8151d845cbf623dd4e2b3/pkg/secrets-store/controllerserver.go#L54)?

**Comment by aramase** [comment]
> adding csi driver capabilities is not threadsafe. This can race with multiple writers or if reading while a concurrent write is executing.

We inherited this code from https://github.com/kubernetes-csi/drivers/blob/master/pkg/csi-common/driver.go

> log redaction of secrets is fragile. This is complex and is whitelist based.

We'll look into this and see how we can make it better.

> Controller server races. Read operations need to hold the lock that guards cs.vols.
stylistic comment: Put all of controllerServer methods in the file where controllerServer is declared. Some of them are in utils.go, and controllerserver.go is short enough.

Sure, we'll make the change. Also just to add, the controller server is implemented only for [sanity tests](https://github.com/deislabs/secrets-store-csi-driver/blob/master/test/sanity/sanity_test.go) for the CSI driver.  `secerets-store-csi-driver` only uses the nodeserver. 

> stylistic: move init into handle. Does os.Exit(0) at the end of the main do anything? It looks like it should be removed.
sytlisitc: move main packages out of pkg/ and into a cmd/ directory to designate that they are not shared packages.

We'll make the changes.

> Why use atomic here? Counter doesn't survive restarts. Is that a problem? It looks pretty easy to add volumes with name conflicts.

The controllerserver is a fake implementation. It's only present here for running the [sanity tests](https://github.com/deislabs/secrets-store-csi-driver/blob/master/test/sanity/sanity_test.go) for the CSI driver.

> Why are driver options passed with a mix of env variables and command line arguments?

We'll make a change to make the provider volume path configurable using a flag instead of the env variable.

> What is mock_provider here?

Like I mentioned above, the controllerserver is fake/mock implementation which is solely used for the purpose of running sanity tests against our CSI driver. The `mock_provider` is just a fake provider name we set for the purpose of sanity tests.

@mikedanese Thank you taking the time to review the code. Really appreciate it. Please let us know if these answers the questions.

**Comment by ritazh** [comment]
Closing as all issues have been addressed
